/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package dealornodeal.ui;

import java.awt.Color;

/**
 *
 * @author sebastian & David
 */
public class MoneyListHigh extends javax.swing.JPanel {

    /**
     * Creates new form MoneyListHigh Display
     * 
     */
    public MoneyListHigh(DealornoDealJFrame mainFrame) {
        initComponents();
        this.setBackground(new Color(255, 248, 220));
       
    }
    // Allows us to chancge the image depenting on what value has been opened
    public void labelChangeHigh(int x){
    if(x == 2000){
      jtbmoney14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dealornodeal/Img/2000r.png")));
    }
    if(x == 3000){
     jtbmoney15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dealornodeal/Img/3000r.png")));  
    }  
    if(x == 4000){
      jtbmoney16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dealornodeal/Img/4000r.png")));
    }
    if(x == 5000){
      jtbmoney17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dealornodeal/Img/5000r.png"))); 
    }  
    if(x == 10000){
      jtbmoney18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dealornodeal/Img/10000r.png")));
    }
    
    if(x == 20000){
      jtbmoney19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dealornodeal/Img/2000r.png")));
    } 
     if(x == 25000){
      jtbmoney20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dealornodeal/Img/25000r.png"))); 
    } 
    if(x == 50000){
      jtbmoney21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dealornodeal/Img/50000r.png")));  
    } 
    if(x == 75000){
     jtbmoney22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dealornodeal/Img/75000r.png")));  
    }
    if(x == 100000){
      jtbmoney23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dealornodeal/Img/100000r.png")));  
    }
    if(x == 200000){
     jtbmoney24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dealornodeal/Img/200000r.png")));  
    } 
    if(x == 250000){
     jtbmoney25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dealornodeal/Img/250000r.png")));  
    }
    if(x == 500000){
     jtbmoney26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dealornodeal/Img/500000r.png")));  
    }  
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtbmoney15 = new javax.swing.JLabel();
        jtbmoney16 = new javax.swing.JLabel();
        jtbmoney17 = new javax.swing.JLabel();
        jtbmoney18 = new javax.swing.JLabel();
        jtbmoney19 = new javax.swing.JLabel();
        jtbmoney20 = new javax.swing.JLabel();
        jtbmoney21 = new javax.swing.JLabel();
        jtbmoney22 = new javax.swing.JLabel();
        jtbmoney23 = new javax.swing.JLabel();
        jtbmoney24 = new javax.swing.JLabel();
        jtbmoney25 = new javax.swing.JLabel();
        jtbmoney26 = new javax.swing.JLabel();
        jtbmoney14 = new javax.swing.JLabel();

        jtbmoney15.setBackground(new java.awt.Color(255, 153, 0));
        jtbmoney15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dealornodeal/Img/3000y.png"))); // NOI18N

        jtbmoney16.setBackground(new java.awt.Color(255, 153, 0));
        jtbmoney16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dealornodeal/Img/4000y.png"))); // NOI18N

        jtbmoney17.setBackground(new java.awt.Color(255, 153, 0));
        jtbmoney17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dealornodeal/Img/5000y.png"))); // NOI18N

        jtbmoney18.setBackground(new java.awt.Color(255, 153, 0));
        jtbmoney18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dealornodeal/Img/10000y.png"))); // NOI18N

        jtbmoney19.setBackground(new java.awt.Color(255, 153, 0));
        jtbmoney19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dealornodeal/Img/20000y.png"))); // NOI18N

        jtbmoney20.setBackground(new java.awt.Color(255, 153, 0));
        jtbmoney20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dealornodeal/Img/25000y.png"))); // NOI18N

        jtbmoney21.setBackground(new java.awt.Color(255, 153, 0));
        jtbmoney21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dealornodeal/Img/50000y.png"))); // NOI18N

        jtbmoney22.setBackground(new java.awt.Color(255, 153, 0));
        jtbmoney22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dealornodeal/Img/75000y.png"))); // NOI18N

        jtbmoney23.setBackground(new java.awt.Color(255, 153, 0));
        jtbmoney23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dealornodeal/Img/100000y.png"))); // NOI18N

        jtbmoney24.setBackground(new java.awt.Color(255, 153, 0));
        jtbmoney24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dealornodeal/Img/2000000y.png"))); // NOI18N

        jtbmoney25.setBackground(new java.awt.Color(255, 153, 0));
        jtbmoney25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dealornodeal/Img/250000y.png"))); // NOI18N

        jtbmoney26.setBackground(new java.awt.Color(255, 153, 0));
        jtbmoney26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dealornodeal/Img/500000y.png"))); // NOI18N

        jtbmoney14.setBackground(new java.awt.Color(255, 153, 0));
        jtbmoney14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dealornodeal/Img/2000y.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jtbmoney25, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtbmoney24, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtbmoney23, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtbmoney22, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtbmoney21, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtbmoney20, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtbmoney19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtbmoney18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtbmoney17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtbmoney16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtbmoney15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtbmoney14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtbmoney26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtbmoney14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtbmoney15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtbmoney16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtbmoney17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtbmoney18)
                .addGap(5, 5, 5)
                .addComponent(jtbmoney19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtbmoney20)
                .addGap(8, 8, 8)
                .addComponent(jtbmoney21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtbmoney22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtbmoney23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtbmoney24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtbmoney25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtbmoney26)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jtbmoney14;
    private javax.swing.JLabel jtbmoney15;
    private javax.swing.JLabel jtbmoney16;
    private javax.swing.JLabel jtbmoney17;
    private javax.swing.JLabel jtbmoney18;
    private javax.swing.JLabel jtbmoney19;
    private javax.swing.JLabel jtbmoney20;
    private javax.swing.JLabel jtbmoney21;
    private javax.swing.JLabel jtbmoney22;
    private javax.swing.JLabel jtbmoney23;
    private javax.swing.JLabel jtbmoney24;
    private javax.swing.JLabel jtbmoney25;
    private javax.swing.JLabel jtbmoney26;
    // End of variables declaration//GEN-END:variables
}
