/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package dealornodeal.ui;

import java.awt.Color;



/**
 *
 * @author sebastian & David
 */
public class MoneyListLow extends javax.swing.JPanel {
    private String number;

    /**
     * Creates new form MoneyListLow
     */
    public MoneyListLow(DealornoDealJFrame mainFrame) {
        initComponents();
        this.setBackground(new Color(255, 248, 220));
    }
    // Allows us to chancge the image depenting on what value has been opened
   public void labelChangeLow(int x) {
    if(x == 1){
    jtbmoney1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dealornodeal/Img/1r.png")));
    
    }
    if(x == 2){
     jtbmoney2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dealornodeal/Img/2r.png")));  
    }  
    if(x == 5){
     jtbmoney3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dealornodeal/Img/5r.png")));    
    }  
    if(x == 10){
     jtbmoney4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dealornodeal/Img/10r.png")));  
    }  
    if(x == 20){
    jtbmoney5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dealornodeal/Img/20r.png")));     
    }  
    if(x == 50){
    jtbmoney6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dealornodeal/Img/50r.png")));   
    }  
    if(x == 100){
     jtbmoney7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dealornodeal/Img/100r.png")));   
    }  
    if(x == 150){
     jtbmoney8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dealornodeal/Img/150r.png")));
    }  
    if(x == 200){
    jtbmoney9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dealornodeal/Img/200r.png")));  
    }  
    if(x == 250){
    jtbmoney10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dealornodeal/Img/250r.png")));     
    }  
    if(x == 500){
     jtbmoney11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dealornodeal/Img/500r.png")));  
    }  
    if(x == 750){
     jtbmoney12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dealornodeal/Img/750r.png")));  
    }  
    if(x == 1000){
     jtbmoney13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dealornodeal/Img/1000r.png")));   
    }  
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtbmoney1 = new javax.swing.JLabel();
        jtbmoney2 = new javax.swing.JLabel();
        jtbmoney3 = new javax.swing.JLabel();
        jtbmoney4 = new javax.swing.JLabel();
        jtbmoney5 = new javax.swing.JLabel();
        jtbmoney6 = new javax.swing.JLabel();
        jtbmoney7 = new javax.swing.JLabel();
        jtbmoney8 = new javax.swing.JLabel();
        jtbmoney9 = new javax.swing.JLabel();
        jtbmoney10 = new javax.swing.JLabel();
        jtbmoney11 = new javax.swing.JLabel();
        jtbmoney12 = new javax.swing.JLabel();
        jtbmoney13 = new javax.swing.JLabel();

        jtbmoney1.setBackground(new java.awt.Color(255, 255, 255));
        jtbmoney1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dealornodeal/Img/1y.png"))); // NOI18N
        jtbmoney1.setInheritsPopupMenu(false);

        jtbmoney2.setBackground(new java.awt.Color(255, 255, 255));
        jtbmoney2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dealornodeal/Img/2y.png"))); // NOI18N

        jtbmoney3.setBackground(new java.awt.Color(255, 153, 0));
        jtbmoney3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dealornodeal/Img/5y.png"))); // NOI18N

        jtbmoney4.setBackground(new java.awt.Color(255, 153, 0));
        jtbmoney4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dealornodeal/Img/10y.png"))); // NOI18N

        jtbmoney5.setBackground(new java.awt.Color(255, 153, 0));
        jtbmoney5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dealornodeal/Img/20y.png"))); // NOI18N

        jtbmoney6.setBackground(new java.awt.Color(255, 153, 0));
        jtbmoney6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dealornodeal/Img/50y.png"))); // NOI18N

        jtbmoney7.setBackground(new java.awt.Color(255, 153, 0));
        jtbmoney7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dealornodeal/Img/100y.png"))); // NOI18N

        jtbmoney8.setBackground(new java.awt.Color(255, 153, 0));
        jtbmoney8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dealornodeal/Img/150y.png"))); // NOI18N

        jtbmoney9.setBackground(new java.awt.Color(255, 153, 0));
        jtbmoney9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dealornodeal/Img/200y.png"))); // NOI18N

        jtbmoney10.setBackground(new java.awt.Color(255, 153, 0));
        jtbmoney10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dealornodeal/Img/250y.png"))); // NOI18N

        jtbmoney11.setBackground(new java.awt.Color(255, 153, 0));
        jtbmoney11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dealornodeal/Img/500y.png"))); // NOI18N

        jtbmoney12.setBackground(new java.awt.Color(255, 153, 0));
        jtbmoney12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dealornodeal/Img/750y.png"))); // NOI18N

        jtbmoney13.setBackground(new java.awt.Color(255, 153, 0));
        jtbmoney13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dealornodeal/Img/1000y.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jtbmoney2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtbmoney3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtbmoney4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtbmoney5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtbmoney6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtbmoney7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtbmoney8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtbmoney9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtbmoney10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtbmoney11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtbmoney12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtbmoney13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtbmoney1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtbmoney1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtbmoney2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtbmoney3)
                .addGap(6, 6, 6)
                .addComponent(jtbmoney4)
                .addGap(6, 6, 6)
                .addComponent(jtbmoney5)
                .addGap(5, 5, 5)
                .addComponent(jtbmoney6)
                .addGap(6, 6, 6)
                .addComponent(jtbmoney7)
                .addGap(8, 8, 8)
                .addComponent(jtbmoney8)
                .addGap(6, 6, 6)
                .addComponent(jtbmoney9)
                .addGap(6, 6, 6)
                .addComponent(jtbmoney10)
                .addGap(6, 6, 6)
                .addComponent(jtbmoney11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtbmoney12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtbmoney13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jtbmoney1;
    private javax.swing.JLabel jtbmoney10;
    private javax.swing.JLabel jtbmoney11;
    private javax.swing.JLabel jtbmoney12;
    private javax.swing.JLabel jtbmoney13;
    private javax.swing.JLabel jtbmoney2;
    private javax.swing.JLabel jtbmoney3;
    private javax.swing.JLabel jtbmoney4;
    private javax.swing.JLabel jtbmoney5;
    private javax.swing.JLabel jtbmoney6;
    private javax.swing.JLabel jtbmoney7;
    private javax.swing.JLabel jtbmoney8;
    private javax.swing.JLabel jtbmoney9;
    // End of variables declaration//GEN-END:variables
}
