package dealornodeal.ui;

import java.awt.Color;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * S@author sebastian & David
 * this Panel is set on the main frame 
 */
public class NewGameJPanel extends javax.swing.JPanel  {
    
    private DealornoDealJFrame menu;
    private buttonjPanel btn;
    public int choice = 99;
    private boolean isChoice = false;
   
    public NewGameJPanel(DealornoDealJFrame mainFrame,buttonjPanel buttonjPanel){
        menu = mainFrame;
        btn = buttonjPanel;
        initComponents();
        this.setBackground(new Color(238, 238, 224));
        disAble();
       
        }
    public void changeOutput(String a){
        //lblBankerNum.setText(a);
        }
    // allows us to enable the buttons when the banker choice meathod is called
    public void bankerEnable(){
        btnNoDeal.setEnabled(true);
        btnDeal.setEnabled(true);  
    }
    // allows us to disable the buttons when we have cases still to open
     private void disAble(){
        btnNoDeal.setEnabled(false);
        btnDeal.setEnabled(false); 
    }

  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnExit = new javax.swing.JButton();
        btnNoDeal = new javax.swing.JButton();
        btnDeal = new javax.swing.JButton();

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dealornodeal/Img/exit.png"))); // NOI18N
        btnExit.setBorder(null);
        btnExit.setBorderPainted(false);
        btnExit.setContentAreaFilled(false);
        btnExit.setFocusable(false);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnNoDeal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dealornodeal/Img/nodeal.png"))); // NOI18N
        btnNoDeal.setBorder(null);
        btnNoDeal.setBorderPainted(false);
        btnNoDeal.setContentAreaFilled(false);
        btnNoDeal.setFocusable(false);
        btnNoDeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoDealActionPerformed(evt);
            }
        });

        btnDeal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dealornodeal/Img/deal.png"))); // NOI18N
        btnDeal.setBorder(null);
        btnDeal.setBorderPainted(false);
        btnDeal.setContentAreaFilled(false);
        btnDeal.setFocusable(false);
        btnDeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDealActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 13, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnNoDeal)
                            .addComponent(btnDeal, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnDeal)
                .addGap(18, 18, 18)
                .addComponent(btnNoDeal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(btnExit)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

   // exits the program
    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
    System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnNoDealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoDealActionPerformed
       choice = 2;
        System.out.println("choice 2");
        disAble();
        if (isChoice == false){
        while (menu.bankerChoice(choice)!= 0){   
        }
        choice = 0;
        }else{
        while (menu.lastChoiceCheck(choice)!= 0){   
        }
        choice = 0;
        }
        //btn.enableCases();
    }//GEN-LAST:event_btnNoDealActionPerformed

    private void btnDealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDealActionPerformed
       choice = 1;
       System.out.println("choice 1");
        disAble();
        if (isChoice == false){
        while (menu.bankerChoice(choice)!= 0){   
        }
        choice = 0;
        }else{
        while (menu.lastChoiceCheck(choice)!= 0){   
        }
        choice = 0;
        }
    }//GEN-LAST:event_btnDealActionPerformed
 public void changeButtonMyCase(){
    btnNoDeal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dealornodeal/Img/mycase.png")));
    
    isChoice = true;
 }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeal;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnNoDeal;
    // End of variables declaration//GEN-END:variables

}
